import { fail } from "./fail";
import { EnvContext } from "./env-context";
import { tmpdir } from "os";
import { join } from "node:path";
import { readFile, mkdtemp, writeFile, access, stat, readdir } from "fs/promises";
import { constants as FS_CONSTANTS } from "fs";
import { resolveWorkspacePath } from "./github-workspace";

/**
 * Runs the Codex CLI with the provided prompt and returns the output written
 * to the "last message" file.
 */
export async function runCodex(
  prompt: string,
  ctx: EnvContext,
): Promise<string> {
  const OPENAI_API_KEY = ctx.get("OPENAI_API_KEY");

  const tempDirPath = await mkdtemp(join(tmpdir(), "codex-"));
  const lastMessageOutput = join(tempDirPath, "codex-prompt.md");

  // Use the unified CLI and its `exec` subcommand instead of the old
  // standalone `codex-exec` binary.
  const args = ["/usr/local/bin/codex", "exec"];

  const inputCodexArgs = ctx.tryGet("INPUT_CODEX_ARGS")?.trim();
  if (inputCodexArgs) {
    args.push(...inputCodexArgs.split(/\s+/));
  }

  // The Codex CLI expects the final positional arg to be a path to a prompt file
  // (not an inline multi-line string). Passing the raw string that contains
  // newlines was causing the CLI to attempt to open a file whose name literally
  // included newline characters, leading to `No such file or directory (os error 2)`.
  // To fix this we persist the prompt to a temporary file and pass its path.
  const promptFile = join(tempDirPath, "prompt.md");
  await writeFile(promptFile, prompt, "utf8");
  args.push("--output-last-message", lastMessageOutput, promptFile);

  const env: Record<string, string> = { ...process.env, OPENAI_API_KEY };
  const INPUT_CODEX_HOME = ctx.tryGet("INPUT_CODEX_HOME");
  if (INPUT_CODEX_HOME) {
    const resolved = resolveWorkspacePath(INPUT_CODEX_HOME, ctx);
    try {
      const st = await stat(resolved);
      if (!st.isDirectory()) {
        console.warn(
          `Specified CODEX_HOME is not a directory: '${resolved}'. Running without CODEX_HOME.`,
        );
      } else {
        try {
          const entries = await readdir(resolved);
          if (entries.length === 0) {
            console.warn(
              `Specified CODEX_HOME directory is empty: '${resolved}'. Running without CODEX_HOME.`,
            );
          } else {
            env.CODEX_HOME = resolved;
          }
        } catch (e) {
          // If we cannot read the directory, avoid setting CODEX_HOME.
          console.warn(
            `Unable to read CODEX_HOME directory '${resolved}': ${e}. Running without CODEX_HOME.`,
          );
        }
      }
    } catch (e) {
      console.warn(
        `Specified CODEX_HOME path does not exist: '${resolved}'. Running without CODEX_HOME.`,
      );
    }
  }

  // Pre-flight: ensure Codex binary exists; otherwise the generic ENOENT from Bun
  // is hard to interpret.
  try {
    await access("/usr/local/bin/codex", FS_CONSTANTS.X_OK);
    const st = await stat("/usr/local/bin/codex");
    if (st.size < 50000) {
      console.warn(
        `Codex binary size (${st.size} bytes) looks suspiciously small; download may be corrupt.`,
      );
    }
  } catch (e) {
    fail(
      `Codex binary not found or not executable at /usr/local/bin/codex. Earlier download step may have failed. Error: ${e}`,
    );
  }

  console.log(`Running Codex: ${JSON.stringify(args)}`);
  if (env.CODEX_HOME) {
    console.log(`Using CODEX_HOME='${env.CODEX_HOME}'`);
  } else {
    console.log("No CODEX_HOME configured – using Codex defaults.");
  }
  console.log(`Prompt file at: ${promptFile}`);
  console.log(`Last message output path: ${lastMessageOutput}`);
  const result = Bun.spawnSync(args, {
    stdout: "inherit",
    stderr: "inherit",
    env,
  });

  if (!result.success) {
    fail(`Codex failed: see above for details.`);
  }

  // Read the output generated by Codex.
  let lastMessage: string;
  try {
    lastMessage = await readFile(lastMessageOutput, "utf8");
  } catch (err) {
    fail(`Failed to read Codex output at '${lastMessageOutput}': ${err}`);
  }

  return lastMessage;
}
